version: '3'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resez-db
  app:
    image: xw1nchester/resez-backend
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db