version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped

  user-ms-db:
    image: postgres:16
    container_name: user-ms-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./user-ms-db:/var/lib/postgresql/data
    restart: unless-stopped