version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        restart: unless-stopped

    redis:
        image: redis
        ports:
            - '6379:6379'
        restart: unless-stopped
        
    resez-memory-db:
        image: postgres:16
        container_name: resez-memory-db
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./collection-ms-db:/var/lib/postgresql/data
        restart: unless-stopped
        
    resez-socket-db:
        image: postgres:16
        container_name: resez-socket-db
        ports:
            - '5434:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./socket-ms-db:/var/lib/postgresql/data
        restart: unless-stopped

    # resez-memory:
    #     image: xw1nchester/resez-memory
    #     container_name: resez-memory
    #     ports:
    #         - '8083:8080'
    #     environment:
    #         - PORT=8080
    #         - RMQ_URL=amqp://rabbitmq
    #         - DB_HOST=resez-memory-db
    #         - DB_PORT=5432
    #         - DB_USER=postgres
    #         - DB_PASSWORD=postgres
    #         - DB_NAME=postgres
    #         - DB_SYNC=true
    #         - JWT_ACCESS_SECRET=secret
    #         - API_URL=http://localhost:8080/api/memory-ms
    #     depends_on:
    #         - resez-memory-db
    #     restart: unless-stopped

    # resez-gateway:
    #     image: xw1nchester/resez-gateway
    #     container_name: resez-gateway
    #     ports:
    #         - 8080:8080
    #     restart: unless-stopped

    # resez-main:
    #     image: xw1nchester/resez-main
    #     container_name: resez-main
    #     ports:
    #         - '8081:8080'
    #     environment:
    #         - PORT=8080
    #         - ALLOWED_ORIGINS=http://localhost:3000,http://76.76.21.21,https://resez.ru
    #         - DB_NAME=postgres
    #         - DB_USERNAME=postgres
    #         - DB_PASSWORD=postgres
    #         - DB_HOST=resez-main-db
    #         - DB_PORT=5432
    #         - SEQUELIZE_SYNC_MODE=alter
    #         - JWT_ACCESS_SECRET=secret
    #         - JWT_REFRESH_SECRET=secret
    #         - JWT_ACCESS_EXPIRATION=1000000d
    #         - JWT_REFRESH_EXPIRATION=1000000d
    #         - BOT_TOKEN=6387264755:AAFK2OzIZAlXQOdipnSb417mUITFUcv4Ztg
    #         - STATIC_URL=http://localhost:8080/static/
    #         - RMQ_URL=amqp://rabbitmq
    #         - RMQ_EXCHANGE=exchange
    #         - REDIS_URL=redis://redis
    #     depends_on:
    #         - resez-main-db
    #     restart: unless-stopped

    # resez-main-db:
    #     image: postgres:16
    #     container_name: resez-main-db
    #     ports:
    #         - '5433:5432'
    #     environment:
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=postgres
    #     volumes:
    #         - ./main-db:/var/lib/postgresql/data
    #     restart: unless-stopped

    # resez-telegram:
    #     image: xw1nchester/resez-telegram
    #     container_name: resez-telegram
    #     restart: unless-stopped