version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        restart: unless-stopped
    
    collection-ms-db:
        image: postgres:16
        container_name: collection-ms-db
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./collection-ms-db:/var/lib/postgresql/data
        restart: unless-stopped

    # resez-gateway:
    #     image: xw1nchester/resez-gateway
    #     container_name: resez-gateway
    #     ports:
    #         - 8080:8080
    #     restart: unless-stopped

    # resez-main:
    #     image: xw1nchester/resez-main
    #     container_name: resez-main
    #     ports:
    #         - 8081:8080
    #     depends_on:
    #         - resez-main-db
    #     restart: unless-stopped

    # resez-main-db:
    #     image: postgres:16
    #     container_name: resez-main-db
    #     ports:
    #         - 5433:5432
    #     volumes:
    #         - ./main-db:/var/lib/postgresql/data
    #     restart: unless-stopped

    # resez-telegram:
    #     image: xw1nchester/resez-telegram
    #     container_name: resez-telegram
    #     restart: unless-stopped
