openapi: 3.0.0
info:
  title: Notification microservice
  version: 1.0.0
  description: API Documentation for notification microservice
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: number
          example: 1
        nickname:
          type: string
          example: xw1nchester
        avatar:
          type: string
          example: http://localhost:8080/api/static/avatars/1715447451335.jpeg
    File:
      required:
        - url
        - name
        - type
        - size
      type: object
      properties:
        url:
          type: string
          example: http://localhost:8086/api/static/1734957405939.jpeg
        name:
          type: string
          example: dog.jpeg
        type:
          type: string
          example: image/jpeg
        size:
          type: number
          example: 100500
    MessageRequestBody:
      type: object
      properties:
        message:
          type: string
          example: Киффлом
        files:
          type: array
          items:
            $ref: "#/components/schemas/File"
    MessageResponseBody:
      type: object
      properties:
        id: 
          type: number
          example: 1
        message:
          type: string
          example: Киффлом
        type:
          type: string
          enum:
            - Обычное
            - Удаленное
            - Системное
            - Голосовое
            - Видео
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        isEdited:
          type: boolean
          example: false
        sender:
            $ref: "#/components/schemas/User"
        readsCount:
          type: number
          example: 2
        chatId:
          type: number
          example: 1
        files:
          type: array
          items:
            allOf:
              - properties:
                  id:
                    type: number
                    example: 1
              - $ref: "#/components/schemas/File"
    PaginationBodyFields:
      type: object
      properties:
        totalCount:
          type: number
          example: 20
        isLast:
          type: boolean
          example: false
        elementsCount:
          type: number
          example: 5
  parameters:
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 5
    Offset:
      name: offset
      in: query
      required: false
      schema:
        type: integer
        default: 0
    Unread:
      name: unread
      in: query
      required: false
      schema:
        type: boolean
  requestBodies:
    Message:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MessageRequestBody'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

security:
  - BearerAuth: []

paths:
  /api/messenger/message/user/{userId}:
    post:
      tags:
        - Messenger
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: number
      requestBody:
        $ref: "#/components/requestBodies/Message"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponseBody"
        "400":
          description: "Validation Error"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"
  /api/messenger/message/chat/{chatId}:
    post:
      tags:
        - Messenger
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: number
      requestBody:
        $ref: "#/components/requestBodies/Message"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponseBody"
        "400":
          description: "Validation Error"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"