version: '3'

services:
  resez-db:
    image: postgres:16
    container_name: resez-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  resez-app:
    image: xw1nchester/resez-backend
    container_name: resez-app
    ports:
      - 8080:8080
    env_file:
      - .production.env
    depends_on:
      - resez-db
    restart: always

volumes:
  pgdata: