openapi: 3.0.0

info:
  title: File microservice
  version: 1.0.0
  description: API Documentation for file microservice

components:
  schemas:
    File:
      required:
        - success
        - file
      type: object
      properties:
        success:
          type: number
          example: 1
        file:
          required:
            - url
          type: object
          properties:
            url:
              type: string
              example: http://localhost:8086/api/static/1734957405939.jpeg
            name:
              type: string
              example: dog.jpeg
            type:
              type: string
              example: image/jpeg
            size:
              type: number
              example: 100500
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      

security:
  - BearerAuth: []
        
paths:
  /api/upload:
    post:
      tags:
        - Upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        '400':
          description: 'Validation error'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '500':
          description: 'Internal Server Error'
  /api/upload/image-by-url:
    post:
      tags:
        - Upload
      requestBody:
        content:
          application/json:
            schema:
              required:
                - url
              type: object
              properties:
                url:
                  type: string
                  example: https://avatars.mds.yandex.net/i?id=b8fb524b8e248dc083ee2d201d123690d21941e0-10244736-images-thumbs&n=13
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        '400':
          description: 'Validation error'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '500':
          description: 'Internal Server Error'